# -*- coding: utf-8 -*-
"""Facebook_ads_api .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rsc5Y9FBJhml2G1xzGmfmDa9_WZeDzLY
"""

! pip install facebook_business
from facebook_business.api import FacebookAdsApi
from facebook_business.adobjects.adaccount import AdAccount
from facebook_business.adobjects.campaign import Campaign
import pandas as pd

app_id = {{your app id}}
app_secret = {{your app secret}}
access_token = {{your access token}}
FacebookAdsApi.init(app_id, app_secret, access_token)
my_account = AdAccount('act_{{fb_ads_account_id}}')

campaign = Campaign({{id_of_any_of_your_campaign}})
params = {
    'date_preset': 'yesterday',
    'fields': ['campaign_name', 'ad_name', 'impressions', 'inline_link_clicks', 'spend']}

response = campaign.get_insights(params=params)
for i in response:
    df = pd.DataFrame({})
    for col in i:
        df1 = pd.DataFrame({col:[i[col]]})
        df = pd.concat([df, df1], axis=1, sort=True)
display(df)