# -*- coding: utf-8 -*-
"""Web _scraping_iBEX35_GUARDO_EN_EXCEL

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d1pOFbBjWApbTQNLHd8G8bRHA1MDSOJm
"""

#con este notebook podras descragar los datos del ibex diraios y los devolvera en un excel

! pip install requests
! pip install beautifulsoup4

from bs4 import BeautifulSoup
import pandas as pd
import requests
import openpyxl

"""#extraer con estructura

"""

URL = "https://www.bolsamadrid.es/esp/aspx/Mercados/Precios.aspx?indice=ESI100000000"
page = requests.get(URL)
resultado = BeautifulSoup(page.text, 'lxml')
resultado

table1 = resultado.find("table", id="ctl00_Contenido_tblAcciones")
table1

# Obtain every title of columns with tag <th>
headers = []
for i in table1.find_all("th"):
 title = i.text
 headers.append(title)
print(headers)

# Create a dataframe
mydata = pd.DataFrame(columns = headers)
mydata

# Create a for loop to fill mydata
for j in table1.find_all("tr")[1:]:
 row_data = j.find_all("td")
 row = [i.text for i in row_data]
 length = len(mydata)
 mydata.loc[length] = row
mydata

escrito = pd.ExcelWriter('Ibex.xlsx')
# escribir el DataFrame en excel
mydata.to_excel(escrito,startrow=0)
# guardar el excel
escrito.save()
print('El DataFrame se ha escrito con éxito en el archivo de Excel.')